export { default as Home } from './home/Home'
export { default as PostDetail } from './postDetail/PostDetail'
export { default as WriteBlog } from './writeBlog/WriteBlog'
export { default as Login } from './login/Login'
export { default as Register } from './register/Register'
export { default as About } from './about/About'
export { default as Contact } from './contact/Contact'